/*    cryptage.h    */
#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>  
#include <ctype.h>
#include <conio.h>
#include <dlgs.h>    
#include <direct.h>
#include <dos.h>
#include <io.h>
#include <fcntl.h>
#include <math.h>
#include <malloc.h>
#include <memory.h>
#include <mmsystem.h>
#include <process.h>
#include <shellapi.h>
#include <signal.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <sys/types.h>
#include <sys/timeb.h>
#include <sys/stat.h>
